### ISSUE TITLE
Include new font

### ISSUE THREAD

**Issue by graphefruit** [QuantumBytesInc/RelicsOfAnnorath#52]
After we're creating a new and own font we need to add this one to our game.

- [ ] Extend CSS that there can be used multiple font's without any problem 
@rotwurstesser1  - This should be easy to do? Do you have a best case scenario for this?

**Comment by rotwurstesser1** [comment]
Hi, well depends, using a fontface kit is always a great way to go but depending on security settings of IE the font will not be loaded unless ROA belongs to the trusted sites, alternatively we can add it to the HTML file itself but with this we have less caching options , also we will need many different fonttypes otherwise we wont be able to display it in all browsers, this is where caching css and fonts become essential it @Sakubik which fonttypes can you generate? Alternatively it can be generated but i have made bad experiences with that.... also we would need to test the font on many different operating systems and browsers (not screens) most css font rendering properties are still not well supported which is why the font itself needs to already be correct and barely any changes to rendering can be made in CSS
-Todo1: Generate all necessary fonttypes
-Todo2: Make a Lorem Ipsum testpage with all Characters and test this on all Browsers on all available OS, mobile and not (Decide if fontface or normal embedding in header)

Notes: bei testing bei mir mit installierter font war die thick teils ein bisschen verpixelt

**Comment by rotwurstesser1** [comment]
Added fonts for all to test 

[fonts.zip](https://github.com/QuantumBytesInc/RelicsOfAnnorath/files/793182/fonts.zip)

**Comment by LarsSaalbach** [comment]
@rotwurstesser1 We just need to support Chrome.
IE,FireFox,Safari won't be included in ROAG, because of CoherentUI

**Comment by rotwurstesser1** [comment]
You said adding on website no?

**Comment by LarsSaalbach** [comment]
Actualy we just want to include it into ROAG (the game) not on ROAP (the portal).

Maybe afterwards we could think about it but it isn't the main target actually.

So we first don't need to care about those other browsers. Also we don't need a big caching for ROAG, because the website is delivered once and won't be reloaded the whole live time. 
If someone caches it will be our amazon servers

**Comment by rotwurstesser1** [comment]
Ok, in that case we stilll need to test Chrome on different OS, I can test on Mac and Win, any Idea how to test on different Linux distros?

**Comment by LarsSaalbach** [comment]
We use the standard Chromium-Engine so there shouldn't be any matter on how the website reacts on different distributions.
Also we just distribute to linux/windows. Mac is excluded atm (AFAIK).
https://en.wikipedia.org/wiki/Chromium_(web_browser)

**Comment by rotwurstesser1** [comment]
Cool! Chrome supports font smoothing which would help us greatly in rendering it coherently for all users. 
http://maxvoltar.com/archive/-webkit-font-smoothing (if interested)

**Comment by graphefruit** [comment]
I changed this to prio low because:
1. We need to get the REST-Framework running
2. We need to get the initial migrations and data done

After this 2 steps the UI is fully working and after this I'll include the font.

**Comment by ManuelGysin** [comment]
First we need to get the font ready.
